name: dart_migrator
description: A postgres migration runner for your Dart projects.
version: 0.1.0
repository: https://github.com/andyhorn/dart_migrator

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  postgres: ^3.1.2
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
